[package]
name = "droppable-rust-icons"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13"
bevy_rapier3d = "0.25"
rand = "0.8.5"
crossbeam = "0.8"